title:        Yphtach Lelkes
tagline:      ''
description:  'Assistant Professor. Annenberg School for Communication. University of Pennsylvania'
url:          http://ylelkes.com
version:      1.1.1
author:
  name:       ''
  email:      ''
markdown:     kramdown
permalink:    pretty
highlighter: rouge
paginate:     5
scholar:
  style: apa
  bibliography: bibliography.bib
  group_by: year
  group_order: descending
# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-52779584-1'
exclude: [Gemfile, Rakefile, README]

